<?php
session_start();
require "./inc/functions.php";

$globalArr = array();

$conn = new PDO("mysql:host=localhost;dbname=pong-game", "pong", "pongPassBoys");

$sql = "SELECT user2 FROM followRel WHERE user1 = ?";

$stmt = $conn->prepare($sql);
$stmt->execute([$_SESSION["id"]]);

$userFollows = $stmt->fetchAll(PDO::FETCH_ASSOC);

//code for getting who is online and not for users following
$userFollowsTime = array();

$sql = "SELECT lastOn, username FROM users WHERE id = ?";

$stmt = $conn->prepare($sql);

$userFollowsUsernames = array();

if (count($userFollows)){
    foreach ($userFollows as $arr){
        $id = $arr["user2"];

        $stmt->execute([$id]);

        $lastOn = $stmt->fetchAll(PDO::FETCH_ASSOC)[0];
        $username = $lastOn["username"];
        $lastOn = getTime((int)$lastOn["lastOn"]);
        
        $userFollowsUsernames[$username] = $id;

        $userFollowsTime[$username] = $lastOn;
    }
}


$sql = "SELECT * FROM followRel WHERE user2 = ?";
$stmt = $conn->prepare($sql);

$stmt->execute([$_SESSION["id"]]);

$followed = $stmt->fetchAll(PDO::FETCH_ASSOC);

foreach ($followed as $id=>$arr){
    $time = $arr["req"];

    $sql = "SELECT username FROM users WHERE id = ?";
    $stmt = $conn->prepare($sql);

    $stmt->execute([$arr["user1"]]);
    
    $result = $stmt->fetch();
    $arr["user1Id"] = $result[0];

    $globalArr[$time] = $arr; 
}

$sql = "SELECT * FROM gameReq WHERE req = ?";

$stmt = $conn->prepare($sql);
$stmt->execute([$_SESSION["id"]]);

$requestedGames = $stmt->fetchAll(PDO::FETCH_ASSOC);

if(count($requestedGames)){
    foreach ($requestedGames as $arr){
        $time = $arr["timeReq"];

        $sql = "SELECT username FROM users WHERE id = ?";

        $stmt = $conn->prepare($sql);
        $stmt->execute([$arr["req"]]);

        $result = $stmt->fetch()[0];
        
        $arr["reqId"] = $result;

        $newArr = array($time => $arr);

        //ensures that the request time generated by the db query will be added without overwriting any other index of the global array
        if (!isset($globalArr[$time])){
            $globalArr[$time] = $arr;
        }
        else { 
            while (true){
                $added = .5;
                if (isset($globalArr[$time + $added])){
                    $added /= 2;
                }
                else {
                    $globalArr[$time + $added] = $arr;
                    break;
                }
            }
        }
    }
}

//sorts the blobal array by the unix timestamp and then reverses it
ksort($globalArr);
$globalArr = array_reverse($globalArr, true);